# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AchievementTaskApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'RealmSwift'
  # Pods for AchievementTaskApp

  target 'AchievementTaskAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AchievementTaskAppUITests' do
    # Pods for testing
  end
target 'WidgetExtension' do
    # Pods for testing
pod 'RealmSwift'
  end


end
